### ISSUE TITLE
Calling Updater.CheckForUpdates() twice throws exception / fails

### ISSUE THREAD

**Issue by rodriada000** [Gabisonfire/avantgarde-lib#4]
The following code will throw an exception or hang. I think it is related to trying to access the ag_files.json file

```csharp
        static void Main(string[] args)
        {
            Updater update = new Updater(AppDomain.CurrentDomain.BaseDirectory);
            update.CheckForUpdates();
            update.CheckForUpdates();
        }
```

**Comment by Gabisonfire** [comment]
Most likely because right after the file is fetched, it is moved to the bin directory.

**Comment by rodriada000** [comment]
I think so. I couldn't get the stack trace because my computer froze and had to restart it but did notice that the ag_files.json file would show as 0KB in app base directory.
